### ISSUE TITLE
Scale UI down if app width exceeds screen width

### ISSUE THREAD

**Issue by alexarje** [fourMs/VideoAnalysis#21]
Testing the Windows build. When starting up on my screen, the main window is slightly to the left of the screen. 

![Screenshot (1)](https://user-images.githubusercontent.com/114316/75428247-2fa3c200-5948-11ea-9c30-2da921159069.png)

**Comment by balintlaczko** [comment]
Wow that's interesting! What is your screen resolution here? From this screenshot it seems to me that the width of the interface might be a bit too big for your screen width and the desktop window manager maybe tried to shuffle it into the view (prioritizing the buttons on the top right corner).
It is quite consistently at the right place on my machine, but that's a 17.4" screen...
Maybe it could be a good idea - since there is not much room to squeeze the UI further without making it a bit too crammed - to scale the interface size a little bit down, like to 90 or 85%. I will look into it.

**Comment by balintlaczko** [comment]
I can confirm that this is an issue (probably on both OS-es in various manifestations) if your screen width resolution is smaller than the interface width. (Perhaps you were running it in a VM?)
The solution to this will be to scale down the interface (ie. the 'zoom') automatically if its default size is larger than the screen width.

**Comment by alexarje** [comment]
This is on my Windows laptop which has a hidpi screen (3800xsomething) and defaults to a 250% presentation resolution.
